version: '3'

services:

  vtiger:
    image: javanile/vtiger:7.1.0
    environment:
      - VT_DEBUG=false
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./:/var/www/html/vtiger/modules/Demo
      - ./languages/en_us/Demo.php:/var/www/html/vtiger/languages/en_us/Demo.php
      - ./includes/main/WebUI.php:/var/www/html/vtiger/includes/main/WebUI.php
      - ./modules/Vtiger/views/List.php:/var/www/html/vtiger/modules/Vtiger/views/List.php
      - ./ajax.html:/var/www/html/vtiger/ajax.html
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8081:8080"

volumes:
  mysql:
